Spec for version 0.1.0
Big-Life-Lab/PHES-ODM-Validation pull request #1
Opened 2022-07-07 18:13 UTC by yulric

2022-07-07 18:33 UTC, DougManuel commented on specs/validation.md
> +* Questions
Yes. Tables will have mandatory headers, but we haven't specified those yet. 
Mandatory header is an important feature. We could embed it into the parts table. I.e. have 'headerM' for mandatory. And 'header' for optional. Or we could put the mandatory headers into the validation rules object. I vote for the `headerM` option. 

also note that different programs may wish to make additional headers mandatory. This means that we have a 'core' ODM validation schema and also there can be additional user defined schema.

2022-07-07 18:37 UTC, DougManuel commented on specs/validation.md
> +    * Is there a document which explains what each of these data types are?
The data types are currently defined here. https://github.com/Big-Life-Lab/PHES-ODM/blob/main/metadata_en.md?plain=1#L24-L32.

However, the approach of version 2 is to make a part for everything that needs a definition. This would mean that we need to add new parts for all data types. @mathew-thomson

2022-07-07 18:40 UTC, DougManuel commented on specs/validation.md
> +    * How do you get the valid categories for a category data type?
All validate categories are defined by `catSetID`. 

For example, `catSetID` = fractionCat has 5 entries (at time of writing). There are three categories with partType = category. These parts are the three valid categories: liquid, mixed, solid.

2022-07-07 18:43 UTC, DougManuel commented on specs/validation.md
> +    * I don't think the "See unit" and "table" data types are valid for this?
Agree. @mathew-thomson looks like an area that needs fixing?

2022-07-07 18:58 UTC, DougManuel approved these changes
We need to define what the Cereberus schema object will be for these features. Meaning, that we should manually create the validation object with the rules for measureReport headers. Then @zargot's task is to generate that validation object from the parts list.

I wonder if we should create that rule set schema as a YAML object rather than a python dictionary. Not sure.

2022-07-08 14:56 UTC, DougManuel commented on specs/validation.md
> +* Questions
https://odm.discourse.group/t/mandatory-fields-for-data-reporting/38/2

2022-07-08 14:57 UTC, DougManuel commented on specs/validation.md
> +    * Is there a document which explains what each of these data types are?
Clarification on data types is here. https://odm.discourse.group/t/dictionary-datatypes/37

2022-07-11 12:28 UTC, yulric commented on specs/validation.md
> +    * I don't think the "See unit" and "table" data types are valid for this?
How can I find the data type for a unit, for example, the `absHumidUnits` unit?

2022-07-11 12:33 UTC, DougManuel commented on specs/validation.md
> +    * I don't think the "See unit" and "table" data types are valid for this?
In the `sets` table search, `absHumidUnits`. There is currently only one unit for this measure, `gm3`.

2022-07-11 12:49 UTC, yulric commented on specs/validation.md
> +    * I don't think the "See unit" and "table" data types are valid for this?
I was looking for a more traditional data type for each unit value, for example, `number` for `gm3`. Or is that not going to be recorded within the ODM?

2022-07-11 20:38 UTC, DougManuel commented on specs/validation.md
> +1. The ODM data to be validated is a [dictionary](https://docs.python.org/3/tutorial/datastructures.html#dictionaries) whose keys are the table names and values are the table rows represented as a [l
Just to be clear or explicit: the ODM data is most often in a CSV format, but it could also be Excel or SQL. I expect the most common workflow in python will be to import ODM data as a Pandas data frame.

We'd then validate the Pandas data frame by converting it to a dictionary? correct? I suppose that a workflow could include converting a CSV to a dictionary, etc.

2022-07-11 20:44 UTC, DougManuel commented on specs/validation.md
> +```{python}
I don't see the table name in this dictionary. How do you know that this table is

2022-07-11 20:58 UTC, DougManuel commented on specs/validation.md
> +        "errorType": "MissingRequiredColumn",
Why is this error "MissingRequiredColumn"? Is this an existing error within the Cerebus package or is this an ODM-specified error? If it is an ODM error, where is the error errorType defined? In which object? 

Below is an actual example of an error from the Cerebus package when there is a missing address field. I think it is totally fine to use the Cereberus default error message, but I expect, we'll need a way (a rule object) that allows us to define error and warning messages and associate them a rule or type of rule (i.e. missing table header). 


```>>> v = Validator()
>>> v.require_all
False

>>> schema = {
...   'name': {'type': 'string'},
...   'a_dict': {
...     'type': 'dict',
...     'require_all': True,
...     'schema': {
...       'address': {'type': 'string'}
...     }
...   }
... }

>>> v.validate({'name': 'foo', 'a_dict': {}}, schema)
False
>>> v.errors
{'a_dict': [{'address': ['required field']}]}

>>> v.validate({'a_dict': {'address': 'foobar'}}, schema)
True
```

2022-07-11 22:14 UTC, DougManuel requested changes
1) Comment on line 150 is the only comment requiring a response. 

However, related to that comment, I think that we need a validation object that contains a description of validation rules and any additional metadata that is required for the validation. I know I've gone back and forth on this topic -- and may continue to go back and forth. The validation metadata could be a simpler version of the current validate.csv. 

- *item*: 1
- *description*: "Validate the column names in a table."
- *messageType*: "error"
- *messageText*: "MissingRequiredColumn"
- *notes*: "This rule is used to validate that the rows in a table have all their mandatory columns. For each table in the data argument, the metadata for this rule is present in the parts sheet in the partID, <table_name>Table, and <table_name>Required column."

I'm tempted to keep what is in the specification document in the final validation document. Meaning, that the ODM documentation would contain a good description and example each(??) validation rule.

2. Suggest removing the files from the repo that are not required for the minimal example. I worry that @zargot will get confused by the current validate.csv and specifications related to the first attempt at the specification.

2022-07-12 12:03 UTC, yulric commented on specs/validation.md
> +1. The ODM data to be validated is a [dictionary](https://docs.python.org/3/tutorial/datastructures.html#dictionaries) whose keys are the table names and values are the table rows represented as a [l
Yes, I was envisioning this function to be the only validation function. We would then provide converter functions for the dataset in CSV, excel, SQL etc. into a Python dictionary.

2022-07-12 12:09 UTC, yulric commented on specs/validation.md
> +        "errorType": "MissingRequiredColumn",
The Cerberus error objects were missing some fields which I thought were required to better understand where the error was coming from and how to fix it. Made sense to me to create out own error objects.

2022-07-12 13:45 UTC, DougManuel commented on specs/validation.md
> +        "errorType": "MissingRequiredColumn",
I am referring to an object to store "MissingRequiredData". I was also wondering about making this more human-readable if it is to be read by a human.

2022-07-12 17:12 UTC, yulric commented on specs/validation.md
> +        "errorType": "MissingRequiredColumn",
The spec for the error object for this particular error is on line 136 to 143. I think it needs a description field though for a human readable message.

The error object will change depending on the error type, but most of the fields will remain the same. I was going to add on to it when adding the remaining features.

2022-07-13 17:35 UTC, yulric commented
@DougManuel @zargot Just a few more changes:

1. Renamed the validation.md file to validate-data.md
2. The second function argument is now a cerberus validation object after discussion with Doug. Updated the rest of the spec.
3. Added a new specification doc (generate-cerberus-schema.md) which goes over the creation of a cerberus object from the ODM data dictionary
4. Remove the old validation files

Let me know if you have any question.

2022-07-13 20:02 UTC, DougManuel commented
@yulric 

1) You were going to create the template for the RuleList.csv, right?

2) We've got slightly used of terms in the document such as `rules` versus `rule list`. I'll see if I can catch them and tidy up. (I made a bunch of those inconsistencies). 

3) 'meta' is great, but we should have a few other elements such as 'ruleID'.

2022-07-14 13:58 UTC, zargot commented on specs/validate-data.md
> +            "addressID: {
missing close-quote

2022-07-14 13:58 UTC, zargot commented on specs/validate-data.md
> +            "addL2: {
missing close-quote

2022-07-14 14:05 UTC, zargot commented on specs/validate-data.md
> +```
cerberus says: `{'Address': ['must be of dict type'], 'Contact': ['must be of dict type']}`?

2022-07-14 14:06 UTC, zargot commented on specs/validate-data.md
> +                "country": "Canada"
missing comma at the end

2022-07-14 14:08 UTC, zargot commented on specs/validate-data.md
> +```
I get the same error with the larger data structure above (line 10)

2022-07-14 14:12 UTC, zargot commented on specs/validate-data.md
> +```
in the "larger on above on line 10" I fixed it by removing the array and just having a single dictionary for Address/Contact, but in this smaller case there are two entries for Address, so that won't work.

2022-07-14 14:55 UTC, zargot commented on specs/validate-data.md
> +```
I think I figured it out. Just adding a list in the schema seems to work.

2022-07-14 14:55 UTC, zargot commented
I'll write a proper review and delete my individual comments, sorry about the mess.

2022-07-15 12:52 UTC, DougManuel commented on metadata/validation-rules-list.csv
> +ruleId,description,messageText
I suggest additional fields for the validation-rule-list.csv. Most of these suggestions are not needed by Joakim and most follow what we are doing in the parts table.
**Additional description fields**-  label and notes in addition to the description. These three fields (labels, description and notes) are the approach used in the parts table.
**fields for versioning** - status (active, inactive), firstReleased (version number i.e. 1.0), lastUpdated, changes (a description of changes from the last version).
**messageType** - warning or error
-  Excel rule - I am not sure about this suggestion. For sure, ODM will have validation in Excel. In version 1 almost all a validation was done in Excel and we had a list of Excel validation rules. We could store the excel rule somewhere else, but I think it makes sense in this file.
- partType - Not sure, but we may want to indicate the part type: i.e. 'table' (MissingMandatoryColumn), 'measures', 'attributes', etc.
- dataFormat (wide, long or mixed) - this may be a feature we can add later because all validation for 1.0 will be for 'long' dataFormat.

2022-07-18 19:30 UTC, yulric commented
@DougManuel @zargot Updated the PR again

* I've added the additional metadata fields to the rules list. I wonder about adding a column called `dictionaryColumnsUsed` where we note down what columns in the template are used to generate the rule
* Updated the specifications to fix the bugs @zargot pointed out. Also added the specification for retrieving the table names from the dictionary.

2022-07-18 21:13 UTC, DougManuel commented on specs/generate-cerberus-schema.md
> +            "addressTable": "PK",
Basically, everything "Table" is being removed and replaced with 'es'. 

See: https://odm.discourse.group/t/table-names-partids-vs-column-names-camelcase-vs-pascalcase/40/14

2022-07-21 15:46 UTC, DougManuel approved these changes
Approving the current state of the specifications.

Flagging:
- @yulric you were going to:
     -  generate specs/process for adding a new rule.
     - generate the specs for the `validationDocs.md` or whatever name and format we want to use for that artifact.

2022-07-25 17:51 UTC, zargot requested changes

2022-07-25 17:51 UTC, zargot commented on specs/validate-data.md
> +* **validationRules**: The ODM data dictionary rule fields violated by this row
should we call this something else? I feel like this name implies that we are listing actual rules, but we are only listing fields that caused the rule violation.

2022-07-25 18:24 UTC, DougManuel commented on .gitignore
> +validationFunction/.DS_Store
Yes.

2022-07-25 18:26 UTC, DougManuel commented on specs/generate-cerberus-schema.md
> +            "addressTable": "PK",
Hopefully, this issue has been fixed and all table that report observations uses plural in the table name. I.e. adressess, contacts, methods, measures...

2022-07-25 18:27 UTC, DougManuel commented on specs/validate-data.md
> +* **validationRules**: The ODM data dictionary rule fields violated by this row
Suggested name?? Of course, the hardest coding task is coming up with a good field name.

2022-07-25 18:45 UTC, zargot commented on specs/validate-data.md
> +* **validationRules**: The ODM data dictionary rule fields violated by this row
True. ;) What about "ruleFields" or "validationRuleFields"?

2022-07-26 11:56 UTC, yulric commented
@zargot I've made your changes, I'll merge this PR and the new-rule-template into main.

2022-07-26 11:56 UTC, merged