implement min/max value rules
Big-Life-Lab/PHES-ODM-Validation pull request #105
Opened 2023-01-10 13:29 UTC by zargot

2023-01-12 18:50 UTC, yulric requested changes
1. I saw you added the type and coerce fields to the schemas for the min/max rules. Can you update specification to reflect this, also adding why its needed.
2. I saw you changed `string` to `str`. We should keep it as string since its more obvious to a non-programmer.
3. Can you add documentation on how all the coercion code works along with why you did that way
4. Can you add descriptions to all the new functions you added? Especially the ones which end in numbers like attr_items2.

2023-01-12 18:50 UTC, yulric commented on src/odm_validation/part_tables.py
> +    return flatten(list(
What do you think about getting a pipe operator library for situations like these with deeply nested function calls. I'm talking about a library like this https://pypi.org/project/pipe/.

2023-01-12 18:50 UTC, yulric commented on src/odm_validation/rule_primitives.py
> +# from pprint import pprint
Delete?

2023-01-12 18:50 UTC, yulric commented on tests/test_min_max_value.py
> +    def test_schema_generation_v1(self, major_ver):
Should this just be `test_schema_generation`?

2023-01-12 18:50 UTC, yulric commented on tests/test_min_max_value.py
> +    def test_pass(self, ix):
test_pass -> test_passing_datasets

2023-01-12 18:50 UTC, yulric commented on tests/test_min_max_value.py
> +    def test_fail(self, ix):
test_fail -> test_failing_datasets

2023-01-12 18:50 UTC, yulric commented on tests/test_min_max_value.py
> +    @parameterized.expand(_param_range(0, 3))
Aren't there only 3 failing datasets?

2023-01-12 19:02 UTC, zargot commented on assets/validation-rules/greater-than-max-value/invalid-dataset-1.yml
> +- siteID: "1"
because the table name can't be part of the data as the code is written now. It's the same with csv files, so I did it to be consistent instead of making an exception for yaml files.

2023-01-12 19:05 UTC, zargot commented on tests/test_min_max_value.py
> +    @parameterized.expand(_param_range(1, 3))
python `range`'s second parameter is not inclusive, so it becomes [1, 2]. I made my _param_range follow the same convention to be consistent with the standard library.

2023-01-12 19:06 UTC, zargot commented on tests/test_min_max_value.py
> +    @parameterized.expand(_param_range(0, 3))
see previous comment about range.

2023-01-12 19:11 UTC, zargot commented on src/odm_validation/validation.py
> +        if rule_key == 'type':
it's a workaround due to not having implemented the invalid_type rule yet, so we don't handle cerberus' type errors. They will come if coercion didn't fix it already, which is why I'm mentioning failed coercion. I can repeat this in a comment for sure.

2023-01-12 19:31 UTC, zargot commented on src/odm_validation/cerberusext.py
> +            logging.error(self.errors)
It's mostly for debugging purposes. You're right that the schema should only be for coercion, and any potential errors also should be coercion errors. I think it's valuable to log any errors there in case it doesn't work as expected, since it's the only output we'll get from the cerberus "coercion" step.

2023-01-12 19:35 UTC, zargot commented on src/odm_validation/part_tables.py
> +    return flatten(list(
Sounds like a good idea. I'll make an issue for a complete refactor.

2023-01-12 19:37 UTC, zargot commented on src/odm_validation/rule_primitives.py
> +# from pprint import pprint
Sure, I can delete them, it's just that i have to add them back every time i debug, haha. What do you think?

2023-01-12 19:42 UTC, zargot commented on src/odm_validation/stdext.py
> +    assert len(dicts) == 0 or isinstance(dicts[0], dict)
It's just to avoid getting errors/bugs that are hard to figure out when the wrong types are being passed to this function. When I experience a debug session like that I tend to add asserts like this. I can remove it once we add static type checking.

2023-01-12 19:43 UTC, zargot commented on tests/test_min_max_value.py
> +    @parameterized.expand(_param_range(1, 3))
see other comment about ranges.

2023-01-12 19:43 UTC, zargot commented on tests/test_min_max_value.py
> +    @parameterized.expand(_param_range(0, 3))
see other comment about ranges.

2023-01-12 21:29 UTC, zargot commented on docs/validation-rules/greater_than_max_value.qmd
> +* **coercionRules**: [greater_than_max_value]
done

2023-01-12 21:29 UTC, zargot commented on docs/validation-rules/less_than_min_value.qmd
> +* **coercionRules**: [less_than_min_value]
done

2023-01-12 21:29 UTC, zargot commented on docs/validation-rules/less_than_min_value.qmd
> +and the following dataset should pass validation with a warning (since by
done

2023-01-12 21:33 UTC, zargot commented on assets/validation-rules/greater-than-max-value/error-report-4.json
> +            "invalidValue": "89",
done

2023-01-12 21:33 UTC, zargot commented on assets/validation-rules/less-than-min-value/error-report-4.json
> +            "invalidValue": "-89",
done

2023-01-12 21:33 UTC, zargot commented on assets/validation-rules/less-than-min-value/error-report-3.json
> +            "invalidValue": "a",
done

2023-01-12 21:33 UTC, zargot commented on assets/validation-rules/greater-than-max-value/error-report-1.json
> +            "invalidValue": 91,
done

2023-01-12 22:44 UTC, zargot commented on src/odm_validation/validation.py
> +def _gen_error_entry(e, row, schema: Schema) -> Optional[str]:
done

2023-01-12 22:45 UTC, zargot commented on src/odm_validation/validation.py
> +        if rule_key == 'type':
done

2023-01-12 22:45 UTC, zargot commented on src/odm_validation/validation.py
> +        assert rule, f'missing rule for constraint "{rule_key}"'
done

2023-01-12 22:45 UTC, zargot commented on src/odm_validation/validation.py
> +        table_schema['meta'] = deduplicate_dict_list(table_schema['meta'])
done

2023-01-12 22:45 UTC, zargot commented on src/odm_validation/cerberusext.py
> +        """Strips `schema` of all rules except 'coerce' and 'meta'."""
done

2023-01-12 22:45 UTC, zargot commented on src/odm_validation/schemas.py
>  def update_schema(schema, table_id, attr_id, rule_id, cerb_rule,
good catch. done.

2023-01-12 22:45 UTC, zargot commented on src/odm_validation/schemas.py
> +            # {
done

2023-01-12 22:46 UTC, zargot commented on tests/test_min_max_value.py
> +    def test_schema_generation_v1(self, major_ver):
done

2023-01-12 22:46 UTC, zargot commented on tests/test_min_max_value.py
> +    def test_pass(self, ix):
done

2023-01-12 22:46 UTC, zargot commented on tests/test_min_max_value.py
> +    def test_fail(self, ix):
done

2023-01-13 17:39 UTC, yulric commented on src/odm_validation/validation.py
> +def _gen_error_entry(e, row, schema: Schema) -> Optional[str]:
This comes back to the point about our static types not being robust, for example, the return type should really be something like `Optional[Error]` but we should address this in another PR.

2023-01-13 17:44 UTC, yulric commented on src/odm_validation/cerberusext.py
> +            logging.error(self.errors)
Could you add a comment?

2023-01-13 17:45 UTC, yulric commented on src/odm_validation/rule_primitives.py
> +# from pprint import pprint
Hmm, ok keep them haha.

2023-01-13 17:46 UTC, yulric commented on src/odm_validation/stdext.py
> +    assert len(dicts) == 0 or isinstance(dicts[0], dict)
Sounds good, but shouldn't this piece `isinstance(dicts[0], dict)` actually check if all the array items are `dict`?

2023-01-13 17:49 UTC, yulric commented on tests/test_min_max_value.py
> +    @parameterized.expand(_param_range(0, 3))
Shouldn't this https://github.com/Big-Life-Lab/PHES-ODM-Validation/blob/37-min-max-value-rules/tests/test_min_max_value.py#L83 be (0,3) then?

2023-01-13 18:12 UTC, yulric requested changes
1. It looks like you forgot to add the `type` and `coerce`  documentation to the greater_than_max_value.qmd file.

2023-01-13 18:12 UTC, yulric commented on src/odm_validation/rule_primitives.py
> +    """Provides a simple way to generate a simple schema. This should be
What constitutes a "sample schema"?

2023-01-13 18:25 UTC, zargot commented on src/odm_validation/rule_primitives.py
> +    """Provides a simple way to generate a simple schema. This should be
updated function docstring :)

2023-01-13 19:26 UTC, zargot commented on src/odm_validation/cerberusext.py
> +            logging.error(self.errors)
done

2023-01-13 19:29 UTC, zargot commented on src/odm_validation/stdext.py
> +    assert len(dicts) == 0 or isinstance(dicts[0], dict)
It would be safest to check all of the items, but I'm being optimistic and assuming that all items in a list have the same type, just to keep it simple, especially when I tend to pretend that it's not allowed to mix types like that when I write code.

2023-01-13 19:32 UTC, zargot commented on tests/test_min_max_value.py
> +    @parameterized.expand(_param_range(0, 3))
good catch! fixed.

2023-01-13 19:34 UTC, yulric approved these changes

2023-01-13 20:11 UTC, merged