fixes #10
Big-Life-Lab/PHES-ODM-Validation pull request #11
Opened 2022-08-19 17:14 UTC by zargot

2022-08-22 20:57 UTC, DougManuel approved these changes
Looks good to me.

2022-08-23 13:58 UTC, yulric requested changes

2022-08-23 13:58 UTC, yulric commented on src/odm_validation/part_tables.py
> +    table_names: List[str]
It looks like the table name is being duplicated between this field and the `table_attr` and `table_catset_attr` fields. What do you think about converting table_names into a dictionary and nesting its categories and attributes into it? We can then retrieve the table names from the dictionary keys.

You could also argue that the same thing is happening with the catset_values and table_catset_attr fields, where the catset names are being duplicated. 

I bring this up because we want to avoid the situation where there are two difference source of truths for the same thing, keeping them synchronized may cause bugs in the future.

2022-08-23 14:29 UTC, zargot commented on src/odm_validation/part_tables.py
> +    table_names: List[str]
You are correct that data is duplicated. It's supposed to be a space-time trade-off, to improve performance by just accessing the information needed. I haven't profiled anything tho, and you have a good point. It's probably beneficial to have a "table" structure with table-specific data, instead of flattening it out like I've been doing. Is it ok if we merge this in as is, and I create a new PR with an attempt at restructuring?

2022-08-23 14:38 UTC, yulric commented on src/odm_validation/part_tables.py
> +    table_names: List[str]
We can always memoized or computed fields (not sure if they're a thing in Python) to save on subsequent executions. But yes, new PR works.

2022-08-23 14:38 UTC, yulric approved these changes

2022-08-23 14:39 UTC, zargot commented on src/odm_validation/part_tables.py
> +    id = get_partID(attr)
Good point. Fixed.

2022-08-23 14:43 UTC, yulric approved these changes

2022-08-23 14:49 UTC, merged