add min/max length rules
Big-Life-Lab/PHES-ODM-Validation pull request #110
Opened 2023-01-11 19:11 UTC by zargot

2023-01-18 18:23 UTC, yulric requested changes

2023-01-18 18:23 UTC, yulric commented on src/odm_validation/validation.py
> +def _get_rule_name(rule: Rule):
I would rename to `_prettify_rule_name`

2023-01-18 18:23 UTC, yulric commented on src/odm_validation/rule_primitives.py
> +def gen_simple_schema(data: pt.PartData, ver, rule_id, odm_key, cerb_key,
Can you add type definitions and documentation for each of these parameters?

2023-01-18 18:23 UTC, yulric commented on assets/validation-rules/greater-than-max-length/error-report.json
> +            "invalidValue": "123-456-111",
Add this field to both specs?

2023-01-18 18:23 UTC, yulric commented on assets/validation-rules/less-than-min-length/schema-v1.yml
> +          minlength: 10
Update line 69 in both specs? minLength -> minlength and maxLength to maxlength

2023-01-18 20:15 UTC, zargot commented on src/odm_validation/validation.py
> +def _get_rule_name(rule: Rule):
done

2023-01-18 20:15 UTC, zargot commented on src/odm_validation/rule_primitives.py
> +def gen_simple_schema(data: pt.PartData, ver, rule_id, odm_key, cerb_key,
done

2023-01-18 20:15 UTC, zargot commented on assets/validation-rules/greater-than-max-length/error-report.json
> +            "invalidValue": "123-456-111",
done

2023-01-18 20:16 UTC, zargot commented on assets/validation-rules/less-than-min-length/schema-v1.yml
> +          minlength: 10
done

2023-01-19 13:33 UTC, yulric approved these changes

2023-01-20 19:51 UTC, merged