implement invalid type rule
Big-Life-Lab/PHES-ODM-Validation pull request #117
Opened 2023-01-21 00:57 UTC by zargot

fixes #78.

This is a very big PR, but it should help to look at the individual commits.

2023-01-23 19:16 UTC, yulric requested changes
1. All the error messages should be formated as "Column <column_name> in row <row_number> in table <table_name> etc. etc.". Can you update everything?

2023-01-23 19:44 UTC, zargot commented on assets/validation-rules/invalid-type/bool-error-report-1.json
> +            "message": "Field in row 1 in column reportable in table measures is a boolean but has value Yes. Allowed values are false/true."
the order of the values is only changed because it was easier to implement. I have to sort them, and that's the default sort order. I can change the sort order if you like.

2023-01-23 19:46 UTC, zargot commented on src/odm_validation/validation.py
> +    target_rule_ids = {rules._COERCION, rules.invalid_category.__name__}
done

2023-01-23 19:50 UTC, zargot commented on src/odm_validation/cerberusext.py
> +        return 'number'
because it's required by the spec ("coerced into a number", etc).

2023-01-23 19:51 UTC, zargot commented on src/odm_validation/rules.py
> +        } | gen_cerb_rules_for_type(val_ctx)
it's a dictionary operator that joins two dictionaries together. In this case it will join 'max' with 'type' (and 'coerce').

2023-01-24 14:31 UTC, yulric commented on assets/validation-rules/invalid-type/bool-error-report-1.json
> +            "message": "Field in row 1 in column reportable in table measures is a boolean but has value Yes. Allowed values are false/true."
Nope, that's fine

2023-01-24 16:20 UTC, zargot commented on assets/validation-rules/invalid-type/bool-error-report-1.json
> +            "message": "Field in row 1 in column reportable in table measures is a boolean but has value Yes. Allowed values are false/true."
done

2023-01-24 16:20 UTC, zargot commented on assets/validation-rules/invalid-type/bool-error-report-2.json
> +            "message": "Field in row 1 in column reportable in table measures is a boolean but has value True. Allowed values are false/true."
done

2023-01-24 16:20 UTC, zargot commented on src/odm_validation/validation.py
> +                       rule_whitelist: List[str] = [],
done

2023-01-24 16:20 UTC, zargot commented on src/odm_validation/validation.py
> +def _gen_error_entry(e, row, schema: Schema, rule_whitelist) -> Optional[dict]:
done

2023-01-24 16:20 UTC, zargot commented on src/odm_validation/validation.py
>      rule = _KEY_RULES.get(rule_key)
done

2023-01-24 16:20 UTC, zargot commented on src/odm_validation/validation.py
> +    odm_kind: str
done

2023-01-24 16:20 UTC, zargot commented on src/odm_validation/cerberusext.py
> +    type_name0 = type_name(type(ctx.value))
done

2023-01-24 16:22 UTC, zargot commented on src/odm_validation/part_tables.py
> +        elif kind == MapKind.CATEGORY or part.get(CATSET_ID) == BOOLEAN_SET:
done

2023-01-24 16:22 UTC, zargot commented on src/odm_validation/rule_primitives.py
> +            kind = attr.get(pt.DATA_TYPE)
done

2023-01-24 16:22 UTC, zargot commented on src/odm_validation/rule_primitives.py
> +    kind: str
done

2023-01-25 20:48 UTC, zargot commented on src/odm_validation/validation.py
> +                                    rule_whitelist=[]
done

2023-01-30 23:09 UTC, yulric commented on src/odm_validation/validation.py
> +    return _transform_rule(rule, column_meta)
Do we need the _transform_rule function or can the logic be appended to this function?

2023-01-30 23:09 UTC, yulric commented on src/odm_validation/rules.py
> +        } | gen_cerb_rules_for_type(val_ctx)
Oh, that's cool! Didn't know that about Python.

2023-01-30 23:10 UTC, yulric requested changes
Just one last comment. Everything else looks good.

2023-01-31 14:04 UTC, yulric approved these changes

2023-01-31 14:47 UTC, merged