Suggested edits to documentation text
Big-Life-Lab/PHES-ODM-Validation pull request #118
Opened 2023-01-22 15:15 UTC by DougManuel

The following changes were made. See below for requested additions from @zargot and @yulric

1. Tutorials were renamed to be more descriptive:
- Tutorial 1 —> Getting started
- Tutorial 2 —> Getting to know the validation library

Edits were made throughout the tutorials. No change in content:
- minor rearrangements in the content. 
- Headings for tutorial 2.
- Grammar and spelling. 

2. Added sections to the index page. The added sections are often found in Python library documentation. A better option may be to put the ‘usage’ section on a separate page. 
- Overview section. This section seems straightforward to add.
- Installation. I recommend we add an installation section. Yes, there is an install section in one of the tutorials, but users expect installation on the main page. I suggest that we keep installation in both the index and tutorial. If we want to install instructions in one place, it would be the main index page.
- Usage. Again this section is somewhat duplicative of the tutorial and explanation guide. These usage sections would be 'how-tos'. Short and to the point.
- FAQ. I suggest that we point people to Discourse and GH Issues. This section seems duplicative of the ‘contributing’ section, but they are different concepts. Thoughts? We would need to add a few FAQs to the Discourse forum. 

@zargot, could you add the missing pieces to the index page?

2023-01-22 15:21 UTC, DougManuel commented
@zargot could you check the links.  I inserted placeholders for a few links. Could you search:
- “insert the link to the missing_mandatory_column rule”
- “insert the link to data type rule”

2023-01-23 13:49 UTC, yulric requested changes
Do we need the Jupyter notebook?

2023-01-23 13:49 UTC, yulric commented on docs/examples/explanation-document/explanation-document.qmd
> +Next, install the two main library functions.
Next, **import** the two main library functions.

2023-01-23 13:49 UTC, yulric commented on docs/examples/explanation-document/explanation-document.qmd
> +The dataset in the next code chunk is a very simple `sites` table as a [CSV file](./datasets/invalid-sites-dataset.csv). The dataset has invalid data since it is missing the mandatory `geoLat` column
`geolat` -> `geoLat`

2023-01-23 13:49 UTC, yulric commented on docs/examples/explanation-document/explanation-document.qmd
> +## Example: validating a validate data table
Should be a third level header? ## -> ###

2023-01-23 13:49 UTC, yulric commented on docs/examples/explanation-document/explanation-document.qmd
> +Generally, you don't need to create a validation schema because there are default OMD validation schemas for all ODM versions. However, you can create your own schema with the `generate_validation_sc
OMD -> ODM?

2023-01-23 17:14 UTC, zargot commented
> Do we need the Jupyter notebook?

I removed it :)

2023-01-23 18:01 UTC, DougManuel commented
> > Do we need the Jupyter notebook?
> 
> I removed it :)

Jupyter files may have been generated during quarto render, but that should only be an intermediate file. Right?

2023-01-24 02:01 UTC, zargot commented on docs/examples/explanation-document/explanation-document.qmd
> +Next, install the two main library functions.
done

2023-01-24 02:01 UTC, zargot commented on docs/examples/explanation-document/explanation-document.qmd
> +The dataset in the next code chunk is a very simple `sites` table as a [CSV file](./datasets/invalid-sites-dataset.csv). The dataset has invalid data since it is missing the mandatory `geoLat` column
done

2023-01-24 02:01 UTC, zargot commented on docs/examples/explanation-document/explanation-document.qmd
> +## Example: validating a validate data table
done

2023-01-24 02:01 UTC, zargot commented on docs/examples/explanation-document/explanation-document.qmd
> +Generally, you don't need to create a validation schema because there are default OMD validation schemas for all ODM versions. However, you can create your own schema with the `generate_validation_sc
done

2023-01-24 02:02 UTC, zargot commented
> > > Do we need the Jupyter notebook?
> > 
> > 
> > I removed it :)
> 
> Jupyter files may have been generated during quarto render, but that should only be an intermediate file. Right?

Yes, that's correct. I added them to the gitignore now. :)

2023-01-30 23:21 UTC, yulric approved these changes

2023-01-31 16:34 UTC, merged