add datetime to min/max-value rules
Big-Life-Lab/PHES-ODM-Validation pull request #130
Opened 2023-02-03 21:30 UTC by zargot

fixes #97

2023-02-07 20:12 UTC, yulric requested changes
1. error-report-4.json should be reverted since its being used in the documentation and its not consistent with the dataset the report is for.
2. Ok, so one issue with the changes you made to all the assets is that the documentation is using them which means it will be confusing to users.

2023-02-07 20:12 UTC, yulric commented on src/odm_validation/reports.py
> +    kind = kind or ctx.kind
ErrorCtx does not have a `kind` field?

2023-02-07 21:28 UTC, zargot commented on src/odm_validation/reports.py
> +    kind = kind or ctx.kind
done

2023-02-08 15:13 UTC, yulric requested changes
1. Can you add tests for generating version 1 schemas?

2023-02-08 20:12 UTC, yulric approved these changes

2023-02-08 20:24 UTC, merged