update parts and schema to rc.3
Big-Life-Lab/PHES-ODM-Validation pull request #131
Opened 2023-02-03 22:19 UTC by zargot

2023-02-17 20:56 UTC, yulric requested changes
1. One of your commits was to remove duplicate entries in the forbidden and allowed fields in the schema. Can you explain why that was hapenning?
2. We should figure out a way to not hardcode the versions for which we need to generate validation schemas. Ideally we would get those from the firstReleased and lastUpdated columns in the dictionary
3. We need to handle multiple values (they're seperated by ;) in the the version 1 columns (version1Table, version1Variable, and version1Category)
4. I'm not sure how the tests for version 2 schemas are passing since the firstReleased and lastUpdated are set to v1 in the code by default? And we're not adding those columns in the test parts 
5. In the tests for invalid_category the following changes should be made
    1. version 1 category parts should have their status "depreciated"
    2. Their firstReleased and lastUpdated should be v1
    3. Their catSetID should be NA
6. We should refactor how the categories are being modelled for version 1 categorical attributes.

Only 3, 4, and 5 are urgent. Everything else can wait.

2023-02-17 20:56 UTC, yulric commented on src/odm_validation/part_tables.py
> +    def _is_cat_v1(p: Part) -> bool:
A version 1 category should also have a version 1 variable

2023-02-20 17:47 UTC, zargot commented
> 1. One of your commits was to remove duplicate entries in the forbidden and allowed fields in the schema. Can you explain why that was hapenning?

The forbidden rule duplication stopped happening for some reason, so i reverted that commit.
Allowed rule duplication seems to come from wrong handling of v1 categories due to them belonging to multiple tables. I've added a FIXME for that.

> 2. We should figure out a way to not hardcode the versions for which we need to generate validation schemas. Ideally we would get those from the firstReleased and lastUpdated columns in the dictionary

I'm assuming this is something we will do in a separate PR. Can you make an issue for it?

> 3. We need to handle multiple values (they're seperated by ;) in the the version 1 columns (version1Table, version1Variable, and version1Category)

Where was this not handled? I can't remember.

> 4. I'm not sure how the tests for version 2 schemas are passing since the firstReleased and lastUpdated are set to v1 in the code by default? And we're not adding those columns in the test parts

This seems to happen due to the logic in `is_compatible` which currently only cares about that the part is active, as long as the schema version is greater than the part version. I'll see if I can fix that now.

> 5. In the tests for invalid_category the following changes should be made
>    
>    1. version 1 category parts should have their status "depreciated"
>    2. Their firstReleased and lastUpdated should be v1
>    3. Their catSetID should be NA

TODO

> 6. We should refactor how the categories are being modelled for version 1 categorical attributes.

I'm assuming you're talking about how the code structures the category data. I agree that we have to improve it.

2023-02-20 17:49 UTC, zargot commented on src/odm_validation/schemas.py
> +    inner = deepcopy(cerb_rules)
done

2023-02-20 21:26 UTC, zargot commented on tools/generate_schemas.py
> +        logging.StreamHandler(),
done

2023-02-20 21:26 UTC, zargot commented on src/odm_validation/part_tables.py
> +def _normalize_key(key: Optional[str]) -> Optional[str]:
done

2023-02-20 21:28 UTC, zargot commented on src/odm_validation/part_tables.py
> +def get_part_active(part) -> bool:
done. I went with `is_active(part)`.

2023-02-20 22:05 UTC, zargot commented on src/odm_validation/part_tables.py
> +def _get_mappings(part: dict, version: Version) -> Optional[List[PartId]]:
here we need to pass `version` to determine if there is a mapping (and should be a mapping) from ODM_VERSION to `version`. If I rename it to `_get_v1_ids`, etc.,  then it doesn't make sense to pass `version` anymore, as this is supposed to determine if we are getting v1 ids or not, so I left the name the same and added a docstring instead. Is that ok?

2023-02-20 22:08 UTC, zargot commented
I'm waiting with any v1 category-related changes until we have cleared up how they should work. ref chat.

2023-02-22 16:57 UTC, yulric requested changes
1. Can we add the status field back into the test files? They should be the source of truth for tests and adding some of the columns in the code is confusing.

2023-02-22 16:57 UTC, yulric commented on src/odm_validation/part_tables.py
> +                    p.get(V1_LOCATION) == 'variableCategories' and
variableCategories should be moved to a variable

2023-02-22 16:57 UTC, yulric commented on src/odm_validation/part_tables.py
> +                attr = all_parts[attr_id]
Rename to `attr_part`

2023-02-22 16:57 UTC, yulric commented on src/odm_validation/part_tables.py
> +                attr_tables = set(_parse_version1Field(attr, V1_TABLE))
Rename to `attr_v1_tables`

2023-02-22 16:57 UTC, yulric commented on src/odm_validation/part_tables.py
> +                attr_vars = set(_parse_version1Field(attr, V1_VARIABLE))
Rename to `attr_v1_vars`

2023-02-22 17:19 UTC, yulric approved these changes

2023-02-22 17:44 UTC, merged