add table data structure
Big-Life-Lab/PHES-ODM-Validation pull request #14
Opened 2022-08-23 15:47 UTC by zargot

fixes #13

2022-08-23 15:51 UTC, zargot commented
I think it will be difficult to restructure the catset data in a good way that doesn't reuse catset-keys. I would argue that it's ok to duplicate ids/keys in general, but it seems to be worth it to group the table-data.

2022-08-25 18:42 UTC, yulric requested changes
Looks good but I'm wondering if the `catset_attr` field can be restructured so that the Dataset field is as below,

```python
{
    attributes: Dataset,
    values: List[str]
    catset_meta: Dict[str, list]
}
```

2022-08-26 18:54 UTC, zargot commented
Thanks, I think I made it work now. :)

2022-08-30 13:33 UTC, yulric approved these changes

2022-08-30 13:47 UTC, merged