add validation error summary
Big-Life-Lab/PHES-ODM-Validation pull request #145
Opened 2023-02-24 20:43 UTC by zargot

fixes #144

2023-03-01 19:35 UTC, yulric requested changes
1. Think we should move all the logic for creating the summary report into a seperate function, in prepearation for the new create_summary_report function that we discussed before.
2. Looking at the new code that requires passing in the ruleId is making me think we should  normalize the Error object so that it should have an error type field (Warning or Error) and a ruleId field. That way you don't have to pass it in everywhere and just get it from the object.

2023-03-01 19:35 UTC, yulric commented on src/odm_validation/validation.py
> +def _record_error(summary: reports.ValidationSummary, table_id, rule_id):
Should move this function to the `ValidationSummary` class? And rename it to `_update_report`?

2023-03-01 19:35 UTC, yulric commented on tools/validate_xlsx.py
> +            result += f'- {count:{width}d} {rule_id}\n'
Add a comment here about why the width is needed.

2023-03-02 18:35 UTC, zargot commented on tools/validate_xlsx.py
> +            result += f'- {count:{width}d} {rule_id}\n'
done

2023-03-02 18:35 UTC, zargot commented on src/odm_validation/validation.py
> +def _record_error(summary: reports.ValidationSummary, table_id, rule_id):
done, i called it count_error

2023-03-02 19:03 UTC, yulric approved these changes

2023-03-02 19:21 UTC, merged