fix sitemeasure table
Big-Life-Lab/PHES-ODM-Validation pull request #159
Opened 2023-03-01 22:06 UTC by zargot

fixes #152, fixes #153 

- fix multi-values in v1 mappings (related to tables in this case)
- temp fix incorrect table-attr relationship in v1 (should be fixed in next minor release)

2023-03-03 20:43 UTC, yulric requested changes
1. I'm comparing the schemas with whats in the version. Could you check why the following were removed:
    1. collection from the Sample table
    2. siteID from the Sample table
    3. fractionAnalyzed from the WWMeasure table

2023-03-03 20:43 UTC, yulric commented on src/odm_validation/rule_primitives.py
> +        table_schema = init_table_schema(table_id1, table_meta, {})
Shouldn't `init_table_schema` choose whether to pass in table_id9 or table_id1 depending on the `ver`?

2023-03-03 20:43 UTC, yulric commented on src/odm_validation/rule_primitives.py
> +        table_schema = init_table_schema(table_id1, table_meta, {})
Shouldn't we pass in table_id0 in case we need to generate the schema for version 2?

2023-03-03 20:54 UTC, zargot commented on src/odm_validation/rule_primitives.py
> +        table_schema = init_table_schema(table_id1, table_meta, {})
table_id0 should equal table_id1 in v2, I think, since get_mappings are defaulting to the original part id.

2023-03-03 20:56 UTC, zargot commented on src/odm_validation/rule_primitives.py
> +        table_schema = init_table_schema(table_id1, table_meta, {})
same as other comment :)
table_id0 = original id
table_id1 = mapped id, which may be either v1 or v2

2023-03-03 21:26 UTC, zargot commented
> 1. I'm comparing the schemas with whats in the version. Could you check why the following were removed:
>    
>    1. collection from the Sample table

That was due to the wrong casing being used in the table name in the dictionary. It's been fixed there and I've updated the parts/schemas.

>    2. siteID from the Sample table

The only siteID (in version1Variable) i can see belongs to the Site table?
The only part with version1Variable=siteID that I can see is partID=siteID, which only has version1Table=Site, not Sample? In any case, is it still wrong now with the new update?

>    3. fractionAnalyzed from the WWMeasure table

Is it still wrong?

2023-03-07 17:15 UTC, yulric commented on src/odm_validation/rule_primitives.py
> +        table_schema = init_table_schema(table_id1, table_meta, {})
Oh ok, yeah the `table_items` function return is confusing. The mapped ID should always be mapped to its version 1 equivalent or None if its does  not exist, setting it to the version 2 value is confusing, since it does not make sense to map a v2 part to a v2 part.

2023-03-07 17:23 UTC, yulric approved these changes
Thanks for looking into those parts, everything looks good now. SiteID is still an issue, but it looks like an issue in the dictionary.

2023-03-07 17:57 UTC, zargot commented on src/odm_validation/rule_primitives.py
> +        table_schema = init_table_schema(table_id1, table_meta, {})
well, the idea behind the mapping was to abstract away the version and only have 'original' and 'mapped' ids, which would end up as the same id if the source and destination version was the same. This way we can write more concise logic code without as many `if version is 1` branches. Isn't that good?

2023-03-07 18:23 UTC, yulric commented on src/odm_validation/rule_primitives.py
> +        table_schema = init_table_schema(table_id1, table_meta, {})
Yeah, but I'm wondering if its less confusing to move all of that version mapping upstream into gen_partdata for example. Then we only have to deal with versioning in that one function.

2023-03-07 18:28 UTC, merged