add rule blacklist
Big-Life-Lab/PHES-ODM-Validation pull request #164
Opened 2023-03-06 19:33 UTC by zargot

and put it in a "rule filter" together with the existing whitelist

2023-03-16 14:53 UTC, yulric requested changes
1. In an effort to start documenting functions, can you add doccomments for the `_map_cerb_errors`, `_map_aggregated_errors`, `_gen_error_entry`, `_gen_cerb_error_entry`, `_gen_aggregated_error_entry`,  and `_map_cerb_errors` since they have changed
2. Can you update the documentation for the `validate_data` function

2023-03-16 14:53 UTC, yulric commented on src/odm_validation/validation.py
> +class RuleFilter:
We should probably have some kind of validation here to ensure that a rule id is not in both lists? I think otherwise it could cause confusion in the future.

2023-03-16 16:55 UTC, yulric commented on src/odm_validation/validation.py
> +class RuleFilter:
Sounds good.

2023-03-21 14:46 UTC, zargot commented
it should all be resolved now @yulric

2023-03-23 17:54 UTC, merged