rewrite report error messages for consistency
Big-Life-Lab/PHES-ODM-Validation pull request #176
Opened 2023-04-05 04:00 UTC by zargot

fixes #135

2023-04-06 15:30 UTC, yulric requested changes
1. For the duplicate_entries_found rule, there will always be more than 1 row in the error report. Can you update the prefix so that "row" becomes "rows"?
2. For the missing_values_found rule, we should put in the offending value in the message. Maybe change the message after the prefix to, 'Missing value "<value>" found'. To avoid confusion with empty strings, it should be, "Empty string found".

2023-04-06 15:30 UTC, yulric commented on tests/test_reports.py
> +            'message': ('missing_mandatory_column rule violated in '
Shouldn't the row not be in the prefix for a spreadsheet?

2023-04-07 01:36 UTC, zargot commented on tests/test_reports.py
> +            'message': ('missing_mandatory_column rule violated in '
done

2023-04-07 01:36 UTC, zargot commented
> 1. For the duplicate_entries_found rule, there will always be more than 1 row in the error report. Can you update the prefix so that "row" becomes "rows"?
> 2. For the missing_values_found rule, we should put in the offending value in the message. Maybe change the message after the prefix to, 'Missing value "" found'. To avoid confusion with empty strings, it should be, "Empty string found".

all done

2023-04-07 01:46 UTC, zargot commented on tests/test_reports.py
> +            'message': ('missing_mandatory_column rule violated in '
resolving myself, to prepare for release

2023-04-07 01:47 UTC, merged

2023-04-07 01:47 UTC, zargot commented
merging myself, to prepare for release