Added the specification for standardizing the validation rule API
Big-Life-Lab/PHES-ODM-Validation pull request #191
Opened 2023-04-28 20:15 UTC by yulric

The main content is in `validation-rule.qmd`. Everything else are assets that the specification file uses.

2023-05-09 16:09 UTC, zargot requested changes
- make it clear that the validation done by rules is optional and meant for the cases where cerberus needs to be extended
- rename gen_schema to gen_schema_values, as it only returns the values
- maybe specify how the rule key is connected to cerberus. in the current impl only the first key is mapped to cerberus, unless match_all_keys is set, which causes all the keys to match the rule. match_all_keys is currently only needed for the missing_values_found rule.

review not done yet, just saving it.

2023-05-09 17:27 UTC, zargot requested changes

2023-05-09 17:27 UTC, zargot commented on docs/specs/validation-rule.qmd
> +#### Validating data
make it clear that the validation done by rules is optional and meant for the cases where cerberus needs to be extended.

2023-05-09 17:27 UTC, zargot commented on docs/specs/validation-rule.qmd
> +2. `gen_schema`
rename gen_schema to gen_schema_values, as it only returns the values

2023-05-09 17:27 UTC, zargot commented on docs/specs/validation-rule.qmd
> +1. The `get_schema_keys` method would return the list `['type', 'coerce', 'max']`
maybe specify how the rule key is connected to cerberus. in the current impl only the first key is mapped to cerberus, unless match_all_keys is set, which causes all the keys to match the rule. match_all_keys is currently only needed for the missing_values_found rule.

2023-05-09 17:27 UTC, zargot commented on docs/specs/validation-rule.qmd
> +`errorType` field in the object, its either added to the errors or warnings
isn't `errorType` the name of the rule used? warnings have `warningType` instead, iirc.

2023-05-09 17:27 UTC, zargot commented on docs/specs/validation-rule.qmd
> +could return an object only for the `max` schema key.
i suppose this is how you're handling having multiple keys for a rule. instead of only matching the first key in the list, you're moving the responsibility to gen_report where it will ignore the wrong keys?

2023-05-09 17:27 UTC, zargot commented on docs/specs/validation-rule.qmd
> +This is an optional method used to inform the rule when a value has been
i'm assuming that this will only be called when the values differ?

2023-05-10 19:16 UTC, yulric commented on docs/specs/validation-rule.qmd
> +1. The `get_schema_keys` method would return the list `['type', 'coerce', 'max']`
The use case for this is handled by `gen_error` as mentioned in this [comment](https://github.com/Big-Life-Lab/PHES-ODM-Validation/pull/191#discussion_r1188912975).

2023-05-10 19:18 UTC, yulric commented on docs/specs/validation-rule.qmd
> +This is an optional method used to inform the rule when a value has been
Value or type (sorry, have to confirm this as a JS dev haha)

2023-05-11 13:02 UTC, zargot commented on docs/specs/validation-rule.qmd
> +`errorType` field in the object, its either added to the errors or warnings
yes :)

2023-05-11 13:03 UTC, zargot commented on docs/specs/validation-rule.qmd
> +This is an optional method used to inform the rule when a value has been
:+1:

2023-05-11 13:05 UTC, zargot commented on docs/specs/validation-rule.qmd
> +`errorType` field in the object, its either added to the errors or warnings
you wrote it correctly in the paragraph around line 300, so if you could correct this one it would be nice.

2023-05-11 13:11 UTC, zargot commented on docs/specs/validation-rule.qmd
> +1. The `get_schema_keys` method would return the list `['type', 'coerce', 'max']`
this is becoming part of the things we need to "think about", so I'm deferring it to later.

2023-05-16 13:33 UTC, yulric commented on docs/specs/validation-rule.qmd
> +`errorType` field in the object, its either added to the errors or warnings
Should be fixed in the latest commit.

2023-12-05 15:37 UTC, merged