impl summarize_report
Big-Life-Lab/PHES-ODM-Validation pull request #196
Opened 2023-05-23 17:21 UTC by zargot

fixes #160 

see commits and their messages.

2023-05-30 13:53 UTC, yulric requested changes

2023-05-30 13:53 UTC, yulric commented on src/odm_validation/rules.py
> +    '_all',
Hmm, not sure this belongs here, its not a rule ID. Shouldn't it go somewhere in the summarization module?

2023-05-30 13:53 UTC, yulric commented on src/odm_validation/summarization.py
> +def summarize_report(report: ValidationReport,
If I understand your code, your're creating an internal data structure which is then used to generate the different pieces of the summary report (overview and summary entries). Can we directly create the summary entries and create the overview from them?

The internal data structure is hard to grok with all its nested layers.

2023-05-30 15:24 UTC, zargot commented on src/odm_validation/rules.py
> +    '_all',
well, it's "all" rule ids, so I think it fits reasonably well, kinda like a default value. If it's not part of RuleId, then I can't use RuleId as the type for 'rule_id' in the SummaryEntry class.

2023-05-30 15:29 UTC, zargot commented on tests/test_summarization.py
> +            'rules': {
hmm. Maybe I misunderstood our conversations earlier. You're talking about `overview.tables.<table>.rules`? I suppose it's the same as summarizing by table, yeah. I'll happily remove it, if you want?

2023-05-30 15:47 UTC, zargot commented on src/odm_validation/summarization.py
> +def summarize_report(report: ValidationReport,
As far as I can see, the overview is already generated from the summary entries?

2023-05-30 17:11 UTC, yulric commented on tests/test_summarization.py
> +            'rules': {
Yeah, it seems redundant to have it in there when they can generate it by passing in `by = Table`.

2023-05-30 17:12 UTC, yulric commented on src/odm_validation/rules.py
> +    '_all',
Sure, I guess it doesn't really matter since all of this will probably change with the `ValidationRule` change.

2023-05-30 17:15 UTC, yulric commented on src/odm_validation/summarization.py
> +def summarize_report(report: ValidationReport,
Do we need the internal data structure? Can we not "directly" create the `ErrorSummary` object without it?

Your right about the overview.

2023-05-30 17:34 UTC, zargot commented on src/odm_validation/rules.py
> +    '_all',
*my face when my code doesn't matter* xD

2023-05-30 17:37 UTC, zargot commented on src/odm_validation/summarization.py
> +def summarize_report(report: ValidationReport,
i can give it a try for sure

2023-05-30 17:56 UTC, zargot commented on tests/test_summarization.py
> +            'rules': {
done

2023-05-31 17:07 UTC, zargot commented on src/odm_validation/summarization.py
> +def summarize_report(report: ValidationReport,
i removed at least one layer of complexity. is it good now?

2023-06-02 14:24 UTC, yulric commented on src/odm_validation/summarization.py
> +                entity_id = [table_id, column_id][key_ix]
This seems less clear then using a ternary operator.

2023-06-02 14:24 UTC, yulric approved these changes
Looks good, thanks for making those changes.

2023-06-02 14:40 UTC, zargot commented on src/odm_validation/summarization.py
> +                entity_id = [table_id, column_id][key_ix]
done :)

2023-06-02 14:53 UTC, merged