impl validate tool
Big-Life-Lab/PHES-ODM-Validation pull request #197
Opened 2023-06-01 13:25 UTC by zargot

Implements the new spec for the validate tool.
 
See commit messages.

2023-06-06 18:01 UTC, yulric requested changes

2023-06-06 19:50 UTC, zargot commented on tools/validate.py
> +    if out_fmt == Format.TXT and out_path:
yeah, I think the only issue is that we have txt as the default parameter arg, which is why I have to do this weird check to guess if it was specified or not. I'm using None as default arg now, which works well I think. (see new commit).

2023-06-06 19:54 UTC, zargot commented on tools/validate.py
> +    out_path = out
what about using the existing in_path var? it matches the other vars better I think. I refactored in a new commit now to make its use consistent.

2023-06-06 19:55 UTC, zargot commented on tools/validate.py
> +        in_paths = preprocess_datafile(data_file, in_fmt)
what's wrong with it? By converting excel to csv we only need code for handling the csv files.

2023-06-06 20:18 UTC, zargot commented on tools/validate.py
> +def info(s="", line=True):
of course :) the line param decides if it should add a newline at the end or not

2023-06-06 20:24 UTC, zargot commented on tools/validate.py
> +            for table_id, table_data in db_data.items():
when outputting to the console i'm writing it out continuously to give feedback to the user as quickly as possible. Imagine validating one small dataset followed by a big one, then the user would want to see the first report while waiting for the next. What do you think?

2023-06-06 20:29 UTC, zargot commented on tools/validate.py
> +        with_console = out_fmt == Format.TXT and not out_path
`with_console` is more like `when_watching_it_in_realtime` and shouldn't really apply when piping to another program or file. I'm not sure how to distinguish that yet, but I can look into if it's possible.

The result will always be written to the console when the out param isn't set, but the yaml and json formats aren't really useful to read in realtime by the user, so I'm only doing the incremental output for the txt format.

2023-06-07 11:56 UTC, yulric commented on tools/validate.py
> +        in_paths = preprocess_datafile(data_file, in_fmt)
Correct me if I'm wrong but right now, the excel file data would be read twice:

1. Once when its being converted to CSV; and
2. Second when its being converted into a Python data structure for validation.

This is an inefficient way of providing a common interface for the tool to work with the data file. I recommend either:

1. Functions that switches its logic depending on the file format; or
2. Polymorphism using interfaces/classes

2023-06-07 11:59 UTC, yulric commented on tools/validate.py
> +def info(s="", line=True):
Does it add a newline or just a space? Because the `end` parameter is ` ` and not `\n`

2023-06-07 13:27 UTC, zargot commented on tools/validate.py
> +def info(s="", line=True):
the default print behavior is end='\n' and flush=false, so im specifying end='' and flush=true when it's not a full line

2023-06-07 13:51 UTC, zargot commented on tools/validate.py
> +        with_console = out_fmt == Format.TXT and not out_path
done

2023-06-07 14:30 UTC, yulric approved these changes

2023-06-07 15:56 UTC, merged