impl summarize tool
Big-Life-Lab/PHES-ODM-Validation pull request #199
Opened 2023-06-05 19:39 UTC by zargot

2023-06-05 19:40 UTC, zargot commented
will be rebased on dev before merge

2023-06-06 19:52 UTC, zargot commented
needs rebase before review, due to new changes in validate-tool PR

2023-06-08 15:37 UTC, yulric requested changes
* Regarding the _DEBUG field, 
    * It looks like it has two purposes:
        1. To stop the addition of the `validationRuleFields` when _DEBUG is false.
        2. To stringify any non-string fields in the error report objects when _DEBUG is false.
    * Both of these are needed by the validation and summarization tool.
    * I don't think this warrants the addition of a global _DEBUG flag. The feature is contained within one module (the reports module). Usually, global variables are used for features that span multiple modules, for example a logging module.
    * I would create a function that changes the report object for the two tools
        * This avoids the need for a global variable
        * It moves all this logic to the modules that need it, the two tools.

2023-06-08 15:37 UTC, yulric commented on tools/reportutils.py
> +def write_report(output: IO, report, fmt: ReportFormat):
Can we make sure this file has functions that are used by both the summarization and validation tools? For example the `write_report` function is only used by the validation tool.

2023-06-08 16:56 UTC, zargot commented on src/odm_validation/summarization.py
> +    TABLE = 1, 'table'
the integer values are needed to keep the order (i want the order table-column-row, but they're not in alphabetical order), and the string values are needed for the summarize-tool like you say. I could try to have a separate enum for the summarize-tool to avoid this, but then we need to keep those two enums in sync, which isn't very DRY. I can solve it by re-using lower-case names as values (see new commit: "simplify summarykey").

2023-06-08 16:58 UTC, zargot commented on tools/validate.py
> +    assert in_fmt != DataFormat.XLSX or len(in_paths) == 1, \
well, I guess it doesn't make sense, at least not how the program is set up currently, since we are only processing one set of tables, meaning only one instance of each table. With multiple excel workbooks there will (probably) be multiple instances of the same tables, and I don't have logic for that. I'm not sure anyone would have use for it either. Maybe I'm missing something. What do you think?

2023-06-08 17:01 UTC, zargot commented on tools/validate.py
> +    for path in in_paths:
it would make the code more complex if we were to mix the two input types (csv and excel), and I don't see any need for that functionality. What do you think?

2023-06-08 17:04 UTC, zargot commented on tools/summarize.py
> +    if in_path:
if no report_file is given, then in_path becomes empty as well, and the tool expects input from stdin. `if in_path` then means "if input comes from a file".

2023-06-08 17:09 UTC, zargot commented on tools/summarize.py
> +def write_csv_summary(sum_report, output):
good catch! I made the summarykey text lower-case as well. (see new commit "fix summarize csv")

2023-06-08 17:10 UTC, zargot commented on src/odm_validation/summarization.py
> +    TABLE = 1, 'table'
the integer values are needed to keep the order (i want the order table-column-row, but they're not in alphabetical order), and the string values are needed for the summarize-tool like you say. I could try to have a separate enum for the summarize-tool to avoid this, but then we need to keep those two enums in sync, which isn't very DRY. I can solve it by re-using lower-case names as values (see new commit: "simplify summarykey").

2023-06-08 17:32 UTC, zargot commented on tools/reportutils.py
> +def write_report(output: IO, report, fmt: ReportFormat):
done in new commit ("move write_report")

2023-06-08 18:25 UTC, zargot commented on tests/common.py
> +        validation._DEBUG = True
that's a great suggestion! I didn't like how it was either. see new commit ("move constants to settings"). :)

2023-06-08 18:40 UTC, zargot commented
> * Regarding the _DEBUG field,
>   
>   * It looks like it has two purposes:
>     
>     1. To stop the addition of the `validationRuleFields` when _DEBUG is false.
>     2. To stringify any non-string fields in the error report objects when _DEBUG is false.
>   * Both of these are needed by the validation and summarization tool.
>   * I don't think this warrants the addition of a global _DEBUG flag. The feature is contained within one module (the reports module). Usually, global variables are used for features that span multiple modules, for example a logging module.
>   * I would create a function that changes the report object for the two tools
>     
>     * This avoids the need for a global variable
>     * It moves all this logic to the modules that need it, the two tools.

the debug constant doesn't do any "stringification" as far as I can see. In the report it only controls the addition of `validationRuleFields` and `row`/`rows`. The main reason for having it as a constant is that otherwise i have to pass it around all the functions and it becomes very messy and unnecessary, especially when it's a constant value.

I've also normalized its use now and removed the "debug" field from errorctx to make it cleaner (see commit "remove debug from errorctx").

I don't think there's an easy way to avoid having a constant for turning on/off debug when the debug stuff is so ingrained in the code, also, we need it to be a public global to allow the user to turn it on and off (as well as in the tests). It's gonna be very inconvenient to pass a debug-flag around the code, like I mentioned earlier.

What do you think?

2023-06-09 13:23 UTC, yulric commented on tools/validate.py
> +    assert in_fmt != DataFormat.XLSX or len(in_paths) == 1, \
I think there are ways to implement this but, yes, we can worry about it later.

2023-06-09 16:14 UTC, merged