Added the template and steps for adding new rules
Big-Life-Lab/PHES-ODM-Validation pull request #2
Opened 2022-07-21 15:50 UTC by yulric

The specs/validation-rules/index.md contains the steps for adding a new rule

2022-07-21 16:48 UTC, DougManuel commented on specs/validation-rules/index.md
> +This folder contains the specifications for all the validation rules currently supported by the ODM. Each file contains information about one rule which includes:
Add header 1 to the file. Maybe '#How to add a new validation rule to the ODM"
then '##Getting started"

2022-07-21 16:51 UTC, DougManuel commented on specs/validation-rules/index.md
> +1. How to convert the data dictionary rows into the cerberus schema for the rule and
I expect 60 to 80 percent of rules will be developed from the dictionary, but there will more/other reference information. OK to keep it as is for now, because the initial rules will all come from the dictionary.

2022-07-21 17:03 UTC, DougManuel commented on specs/validation-rules/index.md
> +    The simplest method is to create a copy of the [missing-mandatory-column.md](./missing-mandatory-column.md) and modifying it
Suggest having the creation of this file a separate step (step 3 as opposed to step 2.4). Then add a description about the different sections of this md file.

2022-07-21 17:08 UTC, DougManuel commented on specs/validation-rules/missing-mandatory-column.md
> +## Generating the cerberus schema
Suggest changing the heading to something like, "## Reference information for the rule". I'd keep the title 'generating the Cerberus schema' but have it as a section around line 122.

2022-07-21 17:10 UTC, DougManuel commented on specs/validation-rules/missing-mandatory-column.md
> +The generated cerberus object is shown below,
This object will be really difficult for most people to create. We'll want it before we code -- or at least an attempt --, but it will likely require a discussion with an analyst who has Cerebus experience.

2022-07-21 17:12 UTC, DougManuel commented on specs/validation-rules/missing-mandatory-column.md
> +The generated cerberus object is shown below,
We will likely generate a few specific rule templates that people can modify. For example, a surveillance program will have a list of labs within their program or a list of public health departments. We'll have an example rule and Cerebus object that they can modify.

2022-07-21 17:12 UTC, DougManuel requested changes
Overall, very much in line with our discussion.
The key elements are all described. The missing-mandatory-column.md is what I envisioned. 

The description is perhaps a bit too technical, but we can refine it if needed in a later version, if needed.  

- Suggest index.md --> README.md
- The example Cerebrus object in the MD is important but challenging. Most people won't be able to create this document, but they need to provide enough information that an analyst with Cerberus experiment can interpret what they want and then generate an example. I suggest that we put this sort of language in the index.MD. meaning great description around 2.4.
-

2022-07-21 18:32 UTC, yulric commented on specs/validation-rules/index.md
> +    The simplest method is to create a copy of the [missing-mandatory-column.md](./missing-mandatory-column.md) and modifying it
Whoop, that was not formatted correctly. I'll fix it.

2022-07-22 10:22 UTC, DougManuel commented
OK. My apologies. I went way too overboard in suggestions. I won't be surprised if we'll revert what I've done. I had difficulty imagining how someone would pr or fork the repo and where the document and files would sit within the overall repo and package. 

I don't think what I've suggested quite works, but hopefully, my suggestions will the discussion. The starting point for the folder and documentation structure was described nicely by @zargot the`zargot/dev` branch. I think we should move that branch to main to help us build from it. 

We had a meeting with some of our users and surveillance programs. Some of my comments and approach to the template were written with them in mind.

2022-07-22 18:39 UTC, yulric commented
@DougManuel Everything looks good to me. Should I merge this in?

2022-07-22 18:41 UTC, DougManuel commented
Yes. Go ahead and merge if you are happy. As mentioned. I would be grateful if we could have the documentation for the repo -- essentially all of the PR -- go to main pretty quickly. We'll want to review with external partners who don't know their way around too much. As well, it would be nice to review the overall file structure with code and documentation.

2022-07-22 18:45 UTC, DougManuel commented
I just saw @zargot 's commit. I had envisioned the python code to generate Cerberus for each rule to be easily identified with the ruleID, etc. I almost wonder if there should be a python function for each rule. NS. I'll let you and @zargot ponder.

2022-07-22 18:45 UTC, DougManuel approved these changes

2022-07-26 11:59 UTC, merged