add quarto tutorial
Big-Life-Lab/PHES-ODM-Validation pull request #21
Opened 2022-08-31 16:36 UTC by zargot

fixes #6

2022-09-04 12:29 UTC, DougManuel reviewed
Looks good. 

Consider starting with a minimal example like the text below, and then go into more complex examples such as changing directories and prettier print. 

I'd probably put the 'generating a schema' into a different file that would focus just on that. Not sure.  

```
samples = utils.import_dataset(join("assets/v2/samples-invalid.csv"))
data = {"samples": samples}
errors = validate_data(schema, data)
```

2022-09-04 12:31 UTC, DougManuel commented
Just a small issue. The convention for the ODM is `[table]_[part]` not  `[table].[part]`. We do that because using `_` generates a valid name in all programming languages. (`.`) does not.

2022-09-04 12:32 UTC, DougManuel approved these changes

2022-09-06 14:49 UTC, yulric requested changes
Looks good, minor housekeeping points.

* Add setup instructions for the package
	* Installing packages in requirements.txt
* Think we should move the qmd file and the tutorial specific assets into its own folder. Don't want the root to get too cluttered.

2022-09-06 16:15 UTC, zargot commented on tutorial.qmd
> +errors = validate_data(schema, data)
fixed

2022-09-06 16:15 UTC, zargot commented on tutorial.qmd
> +`/validation-rules/<rule_name>.md`.
fixed

2022-09-08 12:08 UTC, yulric approved these changes

2022-09-08 14:48 UTC, merged