fix boolean set values in schemas
Big-Life-Lab/PHES-ODM-Validation pull request #235
Opened 2024-11-13 20:14 UTC by zargot

fixes #224

2024-11-21 16:04 UTC, yulric requested changes
1. I think the dictionary for v2.0.0 should be updated to the one one [GitHub](https://github.com/Big-Life-Lab/PHES-ODM/blob/main/Archived%20V2.0/ODM_parts_v2.0.0.csv). The one you have still contains the lowercase true and false.

2024-11-21 16:04 UTC, yulric commented on src/odm_validation/rule_primitives.py
> +                if set_id == pt.BOOLEAN_SET:
Is this chunk adding the lower case boolean values as alloweable?

2024-11-21 16:28 UTC, zargot commented on src/odm_validation/rule_primitives.py
> +                if set_id == pt.BOOLEAN_SET:
`allowed_ids` is a list of part-ids, and the boolean parts have lower-case part-ids, so I have to make them lower case again here since they're retrieved from the list of allowed values which has upper-case booleans. 

This is basically an edge case I have to cover due to the ODM boolean definition having different case depending on the context.

2024-11-21 16:30 UTC, zargot commented
> 1. I think the dictionary for v2.0.0 should be updated to the one one [GitHub](https://github.com/Big-Life-Lab/PHES-ODM/blob/main/Archived%20V2.0/ODM_parts_v2.0.0.csv). The one you have still contains the lowercase true and false.

Oh, they made it consistent? That would help xD

I'm planning to update the schemas for the next version (0.7). I'll write a note on that issue to refactor this, if it's ok for you to do it this way.

2024-11-26 16:47 UTC, yulric commented on src/odm_validation/rule_primitives.py
> +                if set_id == pt.BOOLEAN_SET:
What are the different contexts which requires different versions of the boolean parts?

2024-11-29 17:38 UTC, yulric approved these changes

2024-11-29 17:39 UTC, merged