allow empty values with minlength & allowed rules
Big-Life-Lab/PHES-ODM-Validation pull request #238
Opened 2024-11-19 16:58 UTC by zargot

depends on #228 

- fixes #226
- fixes #227

see commits

2024-11-22 18:20 UTC, yulric requested changes
1. What's the reason for updating the schema and schema additions files in the module-functions folder?
2. Can you explain why you're using anyof rather than just including `empty = True` directly?

2024-11-22 18:20 UTC, yulric commented on src/odm_validation/rules.py
> +                    'empty': True,
Should't this be added only if the part does not allow missing values?

2024-11-22 18:20 UTC, yulric commented on src/odm_validation/rules.py
> +            return {'anyof': [{'empty': True, 'minlength': val}]}
Shouldn't this be added only if the part does not allow missing values?

2024-11-22 19:42 UTC, zargot commented on src/odm_validation/rules.py
> +                    'empty': True,
well, I don't think we can check that since that would make rules depend on each other, but I'll make a test and see if it works, or if I can fix it.

2024-11-22 19:43 UTC, zargot commented on src/odm_validation/rules.py
> +            return {'anyof': [{'empty': True, 'minlength': val}]}
see other comment.

2024-11-25 17:37 UTC, zargot commented on src/odm_validation/rules.py
> +                    'empty': True,
actually, I misunderstood. `empty: true` means that empty values are allowed, so it's correct like this. I'm still making the test to see if there are any incompatibilities with the missing_values_found rule tho.

2024-11-25 18:04 UTC, zargot commented on src/odm_validation/rules.py
> +                    'empty': True,
I've added the test now, see the last commit. Some warnings/errors overlap, but that's to be expected since all rules are independent.

2024-11-26 17:15 UTC, yulric approved these changes

2024-11-27 15:44 UTC, merged