25 versioning
Big-Life-Lab/PHES-ODM-Validation pull request #28
Opened 2022-09-21 14:12 UTC by zargot

2022-09-22 17:03 UTC, DougManuel commented on requirements.txt
> +semver==3.0.0.dev3
Cool. This is a new library for me.

2022-09-22 17:22 UTC, DougManuel approved these changes
I mostly reviewed the unit test code to see if the functionality meets what I expected from the schema and what I know of the users' use cases. 

Looks all good. 
1) If I understand the code, you are validating whether parts.csv has the correct versioning recorded. Great and important. 

Eventually, I envisioned that we would validate the parts list on a pull request to update the parts list. For that, we'd use our validation package, but we'd probably have a separate schema generated to validate the parts list. @zargot and @yulric , were you thinking the same?

2) Thanks for including an update to the .qmd example and also adding a unit test. Exactly what I was hoping for.

I thought that we probably want to include additional .qmd tutorials for different validation features, such as versioning. So, your current `tutorial.qmd` tutorial could be renamed to `getting_started.qmd` (or something like that), and then we'd have `working_with_versioning.qmd` or something like that. There would eventually be more tutorials such as `making_a_custom_shema.qmd`, etc.

What do you think?

Regardless, good work and I am approving this commit. Don't forget to add to documentation when finished.

2022-09-22 17:56 UTC, zargot commented
@DougManuel I agree with splitting up the tutorial as soon as we get enough content. I didn't think about validating the parts list, but it sounds like a good idea, unless it's unnecessary? I'll defer to yulric.

2022-09-22 18:02 UTC, DougManuel commented
> @DougManuel I agree with splitting up the tutorial as soon as we get enough content. I didn't think about validating the parts list, but it sounds like a good idea, unless it's unnecessary? I'll defer to yulric.

Validating the parts list isn't a priority at this point, but let's keep in mind for the future. You are off to a good start informally validating a few columns within your validation package.

2022-09-23 17:53 UTC, yulric requested changes
Overall looks good!

* Don't think `datasets` is the right folder to put the parts.csv file, may be confusing as users will expect actual ODM datasets. I think the right spot would be `assets/v2/dictionary/parts.csv`.
* Is there a test for the generate_cerberus_schema function for versioning? Ideally there would be a version 1 test for each validation rule.

2022-09-23 17:53 UTC, yulric commented on src/odm_validation/versions.py
> +"""
I would move this comment to be close to the _coerce function

2022-09-26 16:46 UTC, zargot commented on tools/generate_schemas.py
> +LOG_FILE = 'generate_schemas.log'
done

2022-09-26 16:46 UTC, zargot commented on tools/generate_schemas.py
> +    sources = list(p.glob('parts-v*.csv'))
done

2022-09-26 16:46 UTC, zargot commented on specs/module-functions.md
> +	"addresses": {
done

2022-09-26 16:46 UTC, zargot commented on specs/module-functions.md
> +		"partID": "addresses"
done

2022-09-26 16:46 UTC, zargot commented on specs/module-functions.md
> +			"meta": {
done

2022-09-26 16:46 UTC, zargot commented on src/odm_validation/validation.py
> +ODM_LATEST = "2.0.0"
done

2022-09-26 16:46 UTC, zargot commented on src/odm_validation/versions.py
> +        warning(f'missing version defaulted to 1.0.0 for "{id}.{label}"')
done

2022-09-26 16:46 UTC, zargot commented on src/odm_validation/versions.py
> +"""
done

2022-09-29 16:27 UTC, zargot commented
missing version1* field impl. converting back to draft.

2022-10-19 18:12 UTC, yulric requested changes
* Can't find the test for generating the validation schema for missing mandatory column
* Can we also test version 2 validation schema generation? This can be done in another PR.
* From a PR perspective it would be nice if there were clear inputs and ouputs in the tests. For example, in the `invalid_category_impl` function, rather than testing each property individually, doing a deep equal with a previously defined test error report.
* Is there a linting rule to avoid Any? I would like to avoid Any just to make the codebase more clear.
* This is the main comment, although your approach to this feature I think its making the code confusing.  The parts sheet representation in your code is now one of two types, a v1 type which has _original_key and _original_value which is confusing to me and a v2 type which is the normal parts sheet. I think that's confusing because when generating the schema we need to check whether its one type or the other. I think a better approach is generating the schema using the parts sheet as is, and then modifying the schema if the users wants the schema for version 1.

2022-10-27 15:14 UTC, zargot commented on src/odm_validation/part_tables.py
i changed a lot, is this still a thing?

2022-10-27 15:14 UTC, zargot commented on src/odm_validation/validation.py
> +    errors: List[str]
is it ok if i create an issue for this instead?

2022-10-28 14:02 UTC, yulric requested changes
Ok, great, the code is much more cleaner and easier to follow than before, great job!

1. Majority of comments are on variable naming
2. Can you add descriptions for the functions in the rule_primitives file
3. I think import_dataset should be renamed to import_csv_file
4. The biggest concern with the codebase right now is the typing. There are a lot of implicit Anys that I would like to catch as well as some generic types like list and tuple that don't have their generics filled. I would like to catch these in the linter preferrably so we can fix them, but that's for another PR.

2022-10-28 14:56 UTC, zargot commented on src/odm_validation/validation.py
> +    errors: List[str]
done #48

2022-10-28 15:16 UTC, zargot commented on tools/generate_schemas.py
> +    sources = list(p.glob(f'v*/{PARTS_FILENAME}'))
done, if `parts_files` is ok?

2022-10-28 15:17 UTC, zargot commented on tools/generate_schemas.py
> +    for parts_file in sources:
isn't it redundant with both file and path?

2022-10-28 15:20 UTC, zargot commented on tools/generate_schemas.py
> +        version_regex = f'.+/v(.+)/{PARTS_FILENAME}'
done, if the new `parts_path_regex` is as good as a comment :)

2022-10-28 15:21 UTC, zargot commented on src/odm_validation/part_tables.py
> +def gen_partdata(parts: Dataset, version: Version):
done

2022-10-28 15:41 UTC, zargot commented on src/odm_validation/rule_primitives.py
> +    for table_id0, td in data.table_data.items():
i would like it to stay version agnostic. my 0 and 1 notation is just an attempt at the math notation `x_1 = f(x_0)`.

2022-10-28 15:44 UTC, zargot commented on src/odm_validation/rule_primitives.py
> +    keys = ['partID', table_id, pt.table_required_field(table_id)]
done

2022-10-28 15:44 UTC, zargot commented on src/odm_validation/rule_primitives.py
> +    keys = ['partID', 'partType']
done

2022-10-28 16:00 UTC, zargot commented on src/odm_validation/rule_primitives.py
> +def get_attr_meta(attr: pt.Part, table_id: PartId, ver: Version):
is it ok if I keep it like this and refactor when a new rule is added that uses a different set of meta fields?

2022-10-31 12:14 UTC, yulric commented on tools/generate_schemas.py
> +    sources = list(p.glob(f'v*/{PARTS_FILENAME}'))
Well, `parts_files` says to me its a list containing part files whereas parts_file_paths seems explicit

2022-10-31 12:15 UTC, yulric commented on tools/generate_schemas.py
> +    for parts_file in sources:
To me when I see file I think the contents of a file are stored in that variable.

2022-10-31 12:18 UTC, yulric commented on src/odm_validation/rule_primitives.py
> +    for table_id0, td in data.table_data.items():
I would just call it table_id in that case. The 0 in table_id makes it seem like its version 0 of a table_id. Same with attr_id0 variable.

2022-10-31 16:34 UTC, zargot commented on tools/generate_schemas.py
> +    sources = list(p.glob(f'v*/{PARTS_FILENAME}'))
done

2022-10-31 16:34 UTC, zargot commented on tools/generate_schemas.py
> +    for parts_file in sources:
done

2022-10-31 16:35 UTC, zargot commented on src/odm_validation/rule_primitives.py
> +    for table_id0, td in data.table_data.items():
done

2022-10-31 16:35 UTC, zargot commented on src/odm_validation/rule_primitives.py
> +    for attr_id0, cs_data in data.catset_data.items():
done (attr_id and doc)

2022-11-02 12:04 UTC, merged