Added missing_values_found rule
Big-Life-Lab/PHES-ODM-Validation pull request #31
Opened 2022-09-22 19:33 UTC by yulric

Everything should be straightforward. I added a new how-to, finding the mandatory columns for a table.

2022-09-22 20:31 UTC, DougManuel commented
Hmm. We may need a conversation on this one, and I may need to correct or clarify what I've said before. I am going to add @mathew-thomson, @il43 and @jeandavidt to this PR.

The most common scenario for missing data is that the user will forget or omit to include a value for a mandatory field. This means the most common missing data will be ``. What may also be common is `NA`. 

The missingness set will likely be used during database management or by analysts during the data cleaning process when they receive data from a data creator. In this situation, someone cleaning the data will coerce `` to one of the missingness values, such as `nr` "A value could have been recorded, however, it was not."

I don't think we need a part for an empty field, but we need a validation rule. 

What this means for this rule is that we need to check there isn't a blank entry AND that the entry isn't one of the missingness values in the missingness list. In practical terms, we need to use both the Cereberus 'nullable' and also 'forbidden'.

2022-09-22 20:35 UTC, DougManuel commented
As an aside, we may want (or will probably want) to create a process to clean data. It occurred to me that this data cleaning is part of the Cereberus package in the 'coerse' function. We'd probably want this as a separate function and Cereberus schema. Not sure. 

An example of the course or data clean function would be to mutate mandatory fields that have `` to `nr`. There would be a report and mutated data would be returned.

2022-10-07 14:03 UTC, yulric commented
@DougManuel I've updated this spec based on our talk yesterday. Can you take a look?

2022-10-07 18:49 UTC, DougManuel requested changes
Sorry, I was unclear. For a mandatory column, there should be an error if missing, including "", NA, NAN, and other missingness types.

For other non-mandatory fields (later validation rules), we should give a warning for a blank field.

2022-10-07 18:49 UTC, DougManuel commented on metadata/validation-rules-list.csv
> +missing_values_found,Validates that a mandatory column does not have cells with empty cells,This rule ensures that mandatory columns do not contain  empty cells,warning,Mandatory column <column_name>
"does not have cells with empty cells" --> "does not have empty cells"

2022-10-07 18:49 UTC, DougManuel commented on validation-rules/missing_values_found.md
> +            "geoLat": "2"
Yes, identifying a string is better.

2022-10-07 18:49 UTC, DougManuel commented on validation-rules/missing_values_found.md
> +* **message**: Mandatory column <column_name> in table <table_name> has an empty value in row <row_index>. Was this intentional?
Sorry, I was unclear. For a mandatory column, there should be an error if missing, including "", `NA`, and other missingness types. 

For other non-mandatory fields (later validation rules), we should give a warning for a blank field.

2022-10-12 18:41 UTC, yulric commented
@DougManuel I've updated the PR

2022-10-13 09:33 UTC, DougManuel approved these changes
Looks good.

2022-10-13 14:43 UTC, merged