Added new type_validation rule
Big-Life-Lab/PHES-ODM-Validation pull request #35
Opened 2022-09-28 19:18 UTC by yulric

Files should be self-explanatory. 

* I've left datetime for a later date just like the min/max validation
* Haven't filled in `boolean` yet, should we get the allowed `boolean` values from the `booleanUnits` part?

2022-09-30 00:29 UTC, DougManuel requested changes
See comment about dataType = NA.

2022-09-30 00:29 UTC, DougManuel commented on validation-rules/invalid_type.md
> +
Suggest adding a section when dataType is `NA`.

I think that only partID = value can be a header with dataType = NA. We'll need a separate rule...

## NA

NA dataType is not validated with this rule. see NA_type.md TODO

2022-09-30 14:45 UTC, yulric commented on validation-rules/invalid_type.md
> +
By NA, do you mean the set of missing values that the ODM data can have?

2022-09-30 15:36 UTC, DougManuel commented on validation-rules/invalid_type.md
> +
We currently have `NA` in the dataType field for the partID = `value`. The value field is where we enter the value for a measure. These values and corresponding dataTypes can vary depending on the measure. For temperature, the value is a real number. For the presence of a variant, the dataType is a Booleen. 

To validate the 'value' header, we'll need to check the dataType for the partID of the measure. 

We currently indicate "NA", but we could have a different more explicit entry, such as "see measure".

2022-10-06 20:40 UTC, DougManuel commented on validation-rules/invalid_type.md
> +
partID = `value` will be updated to have 'see measure'.

2022-10-06 20:41 UTC, DougManuel approved these changes

2022-10-07 14:08 UTC, yulric commented
@DougManuel I've updated the PR with a note about the "see measure" data type. 

I haven't finished the spec for boolean types, can you answer the question below,

`Haven't filled in boolean yet, should we get the allowed boolean values from the booleanUnits part?`

2022-10-21 12:58 UTC, yulric commented
@DougManuel Bumping this up in case you missed my question

2022-10-27 21:49 UTC, DougManuel commented
> @DougManuel I've updated the PR with a note about the "see measure" data type.
> 
> I haven't finished the spec for boolean types, can you answer the question below,
> 
> `Haven't filled in boolean yet, should we get the allowed boolean values from the booleanUnits part?`

The validation of boolean values for data type is the same approach that we'll use for phone numbers and email, I think.
All these data types are in the parts list, but there is no provision for defining the valid data type. We _could_ add the valid data types in the parts table by making a new valid field, using the max-min field, or even the LaTeX expression field, etc. 

What do you think? 

Probably the easiest approach is to define the validation in, er, the validation.md files using regEx. There are too many data types that we need special validation, and it seems a bit hacky or an overkill to use the solutions that I describe above.

All these dataTypes can be defined using regex, which is supported by Cerberus. 

We'd need to define what is a valid true-false value. Just `TRUE` and `FALSE`, which would be `^(TRUE|FALSE)$` (I think)? Or  case insensitive `^(?i:true|false)$`? See [here](https://9to5answer.com/regex-to-match-quot-true-quot-or-quot-false-quot). 

I am inclined to be specific and say only `TRUE` and `FALSE` with a warning for other cases and an error for entries like `T` and `F`. We could coerse or mutate to `TRUE` and `FALSE` at a later time when we develop that provision or package. 

Note that TRUE and FALSE can also be category responses and that validation would be taken care of using category validation. 

That all said, boolean is a bit complicated in the parts table. I will create a Discourse topic to review with the team.

2022-10-28 12:37 UTC, yulric commented
> > @DougManuel I've updated the PR with a note about the "see measure" data type.
> > I haven't finished the spec for boolean types, can you answer the question below,
> > `Haven't filled in boolean yet, should we get the allowed boolean values from the booleanUnits part?`
> 
> The validation of boolean values for data type is the same approach that we'll use for phone numbers and email, I think. All these data types are in the parts list, but there is no provision for defining the valid data type. We _could_ add the valid data types in the parts table by making a new valid field, using the max-min field, or even the LaTeX expression field, etc.
> 
> What do you think?
> 
> Probably the easiest approach is to define the validation in, er, the validation.md files using regEx. There are too many data types that we need special validation, and it seems a bit hacky or an overkill to use the solutions that I describe above.
> 
> All these dataTypes can be defined using regex, which is supported by Cerberus.
> 
> We'd need to define what is a valid true-false value. Just `TRUE` and `FALSE`, which would be `^(TRUE|FALSE)$` (I think)? Or case insensitive `^(?i:true|false)$`? See [here](https://9to5answer.com/regex-to-match-quot-true-quot-or-quot-false-quot).
> 
> I am inclined to be specific and say only `TRUE` and `FALSE` with a warning for other cases and an error for entries like `T` and `F`. We could coerse or mutate to `TRUE` and `FALSE` at a later time when we develop that provision or package.
> 
> Note that TRUE and FALSE can also be category responses and that validation would be taken care of using category validation.
> 
> That all said, boolean is a bit complicated in the parts table. I will create a Discourse topic to review with the team.

re boolean, I believe there is a boolean part which is categorical with True or False, so we should be able to do that.

re other data types, yes, we should be defining what the valid value/values are for a type, or more appropriately a machine readable definition of the type. For email and phone, I believe a regex would be needed to define the type.

2022-10-28 13:19 UTC, DougManuel commented
Having boolean data type as a category has advantages, but it also potentially changes the structure of the data model. The whole boolean section of the data model is inconsistent and needs a review. I'll post that discussion.

2022-10-28 13:23 UTC, DougManuel commented
https://odm.discourse.group/t/boolean-data-type

2022-11-02 17:23 UTC, DougManuel commented
Good news: A decision for boolean data type! 
1) We will keep it as a data type and not have 'categories' of TRUE and FALSE.
2) We felt we should allow upper and lower case, but coerse to upper case when we a develop coerse method.

Bad news: We realized we need to support languages throughout the ODM validation package. That means parts like table names and categories will need to be valid in different languages. I'll create an issue for this.

2022-11-02 18:42 UTC, DougManuel commented
https://odm.discourse.group/t/language-support-for-categories-and-data-types/75

2022-11-08 13:42 UTC, DougManuel commented
Just a quick note: we've finally sorted out the boolean data type. The Excel parts list has been updated. A final note on Discourse will be added shortly.

We'll try to get the excel sheet over to parts v2 RC-1 ASAP.

2022-11-24 16:32 UTC, yulric commented
@DougManuel I've updated the PR with support for validating the boolean data type. Can you take a look?

2022-11-24 21:23 UTC, DougManuel approved these changes
Looks good. 

I wonder if we should make the part "TRUE" and "FALSE" but that is a discussion with the dictionary team.

2022-11-25 15:44 UTC, DougManuel approved these changes
I didn't render the .qmd file, but it looks very good.

2022-11-25 16:18 UTC, merged