Added toolkit demo notebook for presentation
Big-Life-Lab/PHES-ODM-Validation pull request #44
Opened 2022-10-14 13:18 UTC by yulric

Has the quarto notebook with the demo I'll go through during the presentation.

@zargot I'm using the versioning branch since we want to showcase version 1 schema generation. For some reason the validationRuleFields field is not appearing in the error report? I'm guessing that's not implemented yet?

2022-10-14 14:08 UTC, zargot commented
> For some reason the validationRuleFields field is not appearing in the error report? I'm guessing that's not implemented yet?

I'll look into it.

2022-10-22 10:55 UTC, DougManuel requested changes
I made comments in the code. 

- Note that I couldn't execute the beyond line 70. I am unsure if the error is on my part or a bug. 
- I have comments up to creating your own schema. 
      - Some of my comments apply to the whole document, such as moving to CSV and YAML instead of dictionaries. But I don't think that is a must-do suggestion right now. 
      - The bottom sections looked good, but I didn't give them as close a read as the top. I can do that once I/we sort out the execution issues.

2022-10-22 10:55 UTC, DougManuel commented on examples/presentations/validation-demo.qmd
> +# Allows access to all the installed packages on my computer
Wouldn't it make more sense to note there is a requirements.txt file, with instructions or a pointer to how to use the file?

2022-10-22 10:55 UTC, DougManuel commented on examples/presentations/validation-demo.qmd
> +```{python}
Ideally, we've moved toward presenting the schema as a YAML file. Most of our end users will be R users. Or perhaps just good practice to use YAML instead of a python dictionary?

2022-10-22 10:55 UTC, DougManuel commented on examples/presentations/validation-demo.qmd
> +The above validation schema is actually based on a Python library called [cerberus](https://docs.python-cerberus.org/en/stable/schemas.html). Cerberus does all the validation heavy lifting in the pac
Just an editorial comment that I found it difficult to follow the sentence subject in the paragraph. It was the use of 'it' and sentence parts like "in the package". Which package? The validation or Cerberus? I've made a commit with suggestions.

2022-10-22 10:55 UTC, DougManuel commented on examples/presentations/validation-demo.qmd
> +```{python}
Similar comment as the above schema dictionary. I think this is fine for now, but the test data as a CSV would be better. Didn't @zargot update to a CSV in his tutorial?

2022-10-22 10:55 UTC, DougManuel commented on examples/presentations/validation-demo.qmd
> +validation_schema = {
This object gave me an error. It worked when I added "schema" before "sites" to the dictionary.

2022-10-22 10:55 UTC, DougManuel commented on examples/presentations/validation-demo.qmd
> +validation_result = validate_data(
I had an error running this function.

```
--------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/Users/dmanuel/github/PHES-ODM-Validation/examples/presentations/validation-demo.qmd in line 1
----> 44 validation_result = validate_data(
      45     validation_schema,
      46     invalid_odm_dataset
      47 )

File ~/github/PHES-ODM-Validation/examples/presentations/../../src/odm_validation/validation.py:148, in validate_data(schema, data, data_version)
    143                     for e in attr_errors:
    144                         errors.append(_gen_error_entry(e, row))
    146 return ValidationReport(
    147     data_version=data_version,
--> 148     schema_version=schema["schemaVersion"],
    149     package_version=__version__,
    150     errors=errors,
    151 )

KeyError: 'schemaVersion'
```

2022-10-22 10:55 UTC, DougManuel commented on examples/presentations/validation-demo.qmd
> +```{python}
I couldn't run the notebook from this point forward. But I found that @zargot approach to print for humans was nice, and you go into the metadata quickly. 

Maybe first print the message as:

```
```{python}
assert not report.valid()
for e in report.errors:
    print("- " + e["message"])
```

Then the object walks through the parts of the error message. A key message is the error message is structured so that developers can present with different formatting in different applications (web tools, lab information management systems, etc.)

2022-10-25 15:43 UTC, yulric commented on examples/presentations/validation-demo.qmd
> +# Allows access to all the installed packages on my computer
Sorry, this was an issue my Python was configured. Will fix it.

2022-10-25 18:41 UTC, yulric commented
@DougManuel I've pushed changes to the notebook. Ignore all the files changes and only look at the presentations folder. Changes are below:

1. Fixed the setup code
2. Use YAML and CSV files rather than Python dictionaries
3. Better pretty printing
4. Redid the wording due to second point

Let me know if you're still having issues running the code

2022-10-27 09:51 UTC, DougManuel approved these changes
Looks good. Just a few optional comments for consideration. This presentation complements the existing tutorial. I would call this document an explanatory document. 

@zargot @yulric I suggest we keep this as a permanent part of the package and add this document to the Shpinx documentation. (You may want to modify the first paragraph to say this example explains how validation works.

2022-10-27 09:51 UTC, DougManuel commented on examples/presentations/validation-demo.qmd
> +This document goes along with a presentation made during the weekly ODM development group meeting. It introduces and demoes the ODM validation toolkit.
demoes --> demonstrates ?

2022-10-27 09:51 UTC, DougManuel commented on examples/presentations/validation-demo.qmd
> +# Allows access to all the installed packages on my computer
Add the `rich` library to `requirements.txt`? I suggest we keep the presentation folder a permanent part of the repo (in the main branch). @yulric Were you thinking the same? If so, it makes sense to add rich to requirements.txt>

2022-10-27 09:51 UTC, DougManuel commented on examples/presentations/validation-demo.qmd
> +```{python}
Looks good!

2022-10-27 09:51 UTC, DougManuel commented on examples/presentations/validation-demo.qmd
> +validation_result = validate_data(
👍

2022-10-27 15:28 UTC, zargot commented
> @zargot @yulric I suggest we keep this as a permanent part of the package and add this document to the Shpinx documentation. (You may want to modify the first paragraph to say this example explains how validation works.

Yeah, I agree that it would be good to merge it with the existing tutorial in some way. I can create an issue for it, as it probably requires rewriting a lot of it. Maybe we can wait with completing this PR until after the presentation, and incorporate that issue then.

2022-10-27 15:57 UTC, DougManuel commented
> > @zargot @yulric I suggest we keep this as a permanent part of the package and add this document to the Shpinx documentation. (You may want to modify the first paragraph to say this example explains how validation works.
> 
> Yeah, I agree that it would be good to merge it with the existing tutorial in some way. I can create an issue for it, as it probably requires rewriting a lot of it. ~Maybe we can wait to complete this PR until after the presentation, and incorporate that issue then.~

I like both tutorials. They seem complimentary to me. It is good to review what makes a good tutorial or an explanatory document. This is my go to. We strive to have all four types of documentation. I think tutorials are good when they are short and about a specific task. So, I'd probably split out, for example, making a schema from validating data. Have that as two tutorials. However, this notebook supports a presentation, so it will cover more topics and in more detail.

2022-10-27 16:57 UTC, zargot commented
> I like both tutorials. They seem complimentary to me. It is good to review what makes a good tutorial or an explanatory document. This is my go to. We strive to have all four types of documentation. I think tutorials are good when they are short and about a specific task. So, I'd probably split out, for example, making a schema from validating data. Have that as two tutorials. However, this notebook supports a presentation, so it will cover more topics and in more detail.

If we can keep both that's great. Then it only depends on completing #15.

2022-11-03 17:34 UTC, closed without merging