spec: fix readme links
Big-Life-Lab/PHES-ODM-Validation pull request #75
Opened 2022-11-23 18:10 UTC by zargot

the slash after 'README.md' caused a quarto compile error

2022-11-23 19:08 UTC, yulric requested changes
Sorry, I wanted the #version1 so that it links directly to that section. Can you remove the / before the # to see if that works?

2022-11-23 19:30 UTC, zargot commented
> Sorry, I wanted the #version1 so that it links directly to that section. Can you remove the / before the # to see if that works?

yes, it seems to work!

2022-11-23 19:35 UTC, zargot commented
well, the anchor doesn't work locally for me with `quarto preview`, but it may act differently on github pages with Sphinx.

2022-11-24 17:38 UTC, yulric approved these changes

2022-11-24 17:39 UTC, merged