skip parts that are missing version1 fields
Big-Life-Lab/PHES-ODM-Validation pull request #89
Opened 2022-12-09 15:48 UTC by zargot

when generating a schema for v1, all parts need to have version1 fields

fixes #70.

2022-12-15 18:01 UTC, yulric requested changes
The changes look good but I think we should return a warnings field for the generate_validation_schema function like we do for validate_data. Right now the only warning would be for an invalid version 1 part. Do you want to spec that out in this PR or should I?

2022-12-15 20:49 UTC, zargot commented on src/odm_validation/part_tables.py
> +        pid = get_partID(row)
done

2022-12-15 20:50 UTC, zargot commented
waiting for spec for warning-list.

2023-01-10 13:50 UTC, zargot commented
@yulric Ah, I forgot about this one. Yeah, I think we can merge it. Can you approve it?

2023-01-10 14:03 UTC, yulric approved these changes

2023-01-10 14:53 UTC, merged