Add specifications for generating warnings when generating a validation schema
Big-Life-Lab/PHES-ODM-Validation pull request #94
Opened 2022-12-16 20:21 UTC by yulric

# Why

When generating a validation schema for version 1 datasets, the backported values come from version 1 columns like `version1Location` in the dictionary. Any invalid values in these columns means that we can't generate an entry in the schema for that row. These feature will provide the user with warnings when this happens.

# Files Changed

* The specification file can be seen at `specs/generate-validation-schema.qmd`.
* All the assets for the specifications are at `assets/specs/generate-validation-schema/missing-version-1-fields`.
* Updated the `module-functions.md` file since the return for the generate-validation-schema` function has changed.

2023-01-04 21:39 UTC, DougManuel commented on docs/specs/generate-validation-schema.qmd
> +### Warnings
This warning specification looks good. Please tell the dictionary development team if there are parsing errors of parts.csv. We can correct those. Version 1 won't be updated (hopefully), so correcting errors should be a limited exercise.

2023-01-04 21:41 UTC, DougManuel commented on docs/specs/generate-validation-schema.qmd
> +### Warnings
I don't even think we should generate an error if there isn't a corresponding version 1 equivalent for a version 2 part. We don't have an expectation that there should be equivalency.

2023-01-04 23:37 UTC, yulric commented on docs/specs/generate-validation-schema.qmd
> +### Warnings
> I don't even think we should generate an error if there isn't a corresponding version 1 equivalent for a version 2 part. We don't have an expectation that there should be equivalency.

Even if the `firstReleased` column is 1.0? I thought that if the previous statement is true then there has to be a version 1 equivalent part.

2023-01-05 21:00 UTC, zargot requested changes
should be merged to master, and a new issue should be created, as discussed.

2023-01-10 17:55 UTC, merged